# spring-boot-postgres-flyway/docker-compose.yml
# Code from tutorial: <https://keepgrowing.in/tools/set-up-a-postgresql-database-with-docker/>
version: "3.4"
services:
  postgres:
    image: "postgres:14.0-alpine"
    # official PostgreSQL Docker image
    ports:
      - "5432:5432"
      # HOST:CONTAINER
    volumes:
      - postgres:/var/lib/postgresql/data
      # host file system (/var/lib/docker/volumes/ on Linux) 
      # on the container (/var/lib/postgresql/data)
    environment:
      - POSTGRES_USER=userdocker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=Sadim
    networks:
      - postgres-pgadmin-network

  pgadmin4:
    image: "dpage/pgadmin4:latest"
    # pgadmin4 Docker image
    ports:
      - "5050:80"
      # HOST:CONTAINER
    # volumes:
    #   - pgadmin4:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    networks:
      - postgres-pgadmin-network
    depends_on:
      - postgres
    
networks:
  postgres-pgadmin-network:
    driver: bridge

volumes:
  postgres:
